export const data = [{
    "id": 1,
    "product": "pen",
    "rate": "10",
    "quantity": "20",
    "available": "5",
    "sold": "15"
  }, {
    "id": 2,
    "product": "pencil",
    "rate": "5",
    "quantity": "20",
    "available": "5",
    "sold": "15"
  }, {
    "id": 3,
    "product": "white_copy",
    "rate": "50",
    "quantity": "20",
    "available": "5",
    "sold": "15"
  }, {
    "id": 4,
   "product": "black_copy",
    "rate": "50",
    "quantity": "20",
    "available": "5",
    "sold": "15"
  }, {
    "id": 5,
    "product": "rough_copy",
    "rate": "60",
    "quantity": "20",
    "available": "5",
    "sold": "15"
  }, {
    "id": 6,
    "product": "note_copy",
    "rate": "100",
    "quantity": "20",
    "available": "5",
    "sold": "15"
  }, {
    "id": 7,
   "product": "English_book",
    "rate": "250",
    "quantity": "20",
    "available": "5",
    "sold": "15"
  }, {
    "id": 8,
    "product": "nepali_book",
    "rate": "300",
    "quantity": "20",
    "available": "5",
    "sold": "15"
  }, {
    "id": 9,
    "product": "science_book",
    "rate": "400",
    "quantity": "20",
    "available": "5",
    "sold": "15"
  }, {
    "id": 10,
   "product": "social_book",
    "rate": "380",
    "quantity": "20",
    "available": "5",
    "sold": "15"
  }, {
    "id": 11,
    "product": "Samajik",
    "rate": "10",
    "quantity": "20",
    "available": "5",
    "sold": "15"
  }, {
    "id": 12,
   "product": "color_set",
    "rate": "300",
    "quantity": "20",
    "available": "5",
    "sold": "15"
  }, {
    "id": 13,
   "product": "holder_pen",
    "rate": "10",
    "quantity": "20",
    "available": "5",
    "sold": "15"
  }, {
    "id": 14,
   "product": "black_pen",
    "rate": "10",
    "quantity": "20",
    "available": "5",
    "sold": "15"
  }, {
    "id": 15,
   "product": "blue_pen",
    "rate": "10",
    "quantity": "20",
    "available": "5",
    "sold": "15"
  }, {
    "id": 16,
    "product": "red_pen",
    "rate": "10",
    "quantity": "20",
    "available": "5",
    "sold": "15"
  }, {
    "id": 17,
    "product": "chalk",
    "rate": "10",
    "quantity": "20",
    "available": "5",
    "sold": "15"
  }, {
    "id": 18,
    "product": "marker",
    "rate": "10",
    "quantity": "20",
    "available": "5",
    "sold": "15"
  }, {
    "id": 19,
    "product": "laptop",
    "rate": "100000",
    "quantity": "20",
    "available": "5",
    "sold": "15"
  }]
  